---
title: "events_fighter"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r cars}
# event results
library(rvest)
library(tidyverse)
library(glue)
```

Get all tables

```{r}
url <- "https://www.sherdog.com/fighter/Justin-Gaethje-46648"
read_html(url) %>% html_nodes("table") %>% html_table()
```

Get specific table.

```{r}
read_html(url) %>% html_nodes("body > div.container > div:nth-child(3) > div.col_left > section:nth-child(4) > div > div.content.table") %>% html_children() %>% html_table(header = TRUE) %>% as.data.frame() -> sample_table
```

```{r}
seed_div <- read_html(url) %>% html_nodes("td:nth-child(2) a , .cnaccept") %>% html_attr(.,"href") %>% as.data.frame() %>% unique()
names(seed_div)[1]<-"fighterName"
rownames(seed_div)<-str_split(seed_div$fighterName,"/",simplify = TRUE)[,3]
```

Create Division Crawler

```{r}
fighter_crawler <- function(url){
    base_url <- "https://www.sherdog.com"
    fighter_url <- glue(base_url,"{url}")
    
    tmp <-read_html(fighter_url) %>% html_nodes("td:nth-child(2) a , .cnaccept") %>% html_attr(.,"href") %>% as.data.frame()
    nam<-paste0(fighter_url,"_")
    assign(nam,tmp)
    
}
```

Test Division Crawler

```{r}
seed <- seed_div %>% slice_head(n=8)

map_df(seed$fighterName,fighter_crawler) %>% unique %>% rowid_to_column() -> div_lightweights 
names(div_lightweights)[2]<-"fighterName"
```


Create Results Crawler

```{r}
url_crawler <- function(fighter){
  base_url <- "https://www.sherdog.com"
  
  full_url <- glue(base_url,"{fighter}")
  
  read_html(full_url) %>% 
    html_nodes("body > div.container > div:nth-child(3) > div.col_left > section:nth-child(4) > div > div.content.table") %>% html_children() %>% 
    html_table(header = TRUE, fill=TRUE) %>% 
    as.data.frame()
}

```

Test Results Crawler

```{r}
url_crawler("/fighter/Khabib-Nurmagomedov-56035") -> sample_results

```

Execute over the entire 155lb division. 

```{r}
map_df(div_lightweights$fighterName, url_crawler,.id = "rowid") -> results_lightweights
```


Data Preparation


```{r}
library(stringr)

results_lightweights -> wc
```


```{r}
div_lightweights %>%  mutate(Opponent = str_trim(str_replace_all(str_remove_all(str_split(fighterName,"fighter/",simplify = TRUE)[,2],"[0-9]"),"-"," "))) -> div_lightweights

wc %>% select(rowid:Time) %>% 
  mutate(Method=str_c(str_split(Method.Referee,"[)]",simplify = TRUE)[,1],")")) %>% 
  select(-Method.Referee) %>% rename(Round = R) %>% 
  na.omit -> wc
```

Extract Dates of Events

```{r}
wc %>% mutate(DateEvent= as.Date(str_replace_all(str_replace_all(str_sub(wc$Event,start = -15),"/","-")," ",""),format = "%b-%d-%Y")) -> wc

str_sub(wc$Event,start=-15) <-""
```

Calculate Streaks - Prepare

```{r}

wc[order(wc$DateEvent),] %>% 
  group_by(rowid) %>% 
  mutate(Outcome = case_when(Result=="win" ~ 1, TRUE ~0)) %>% 
  mutate(lagged = lag(Outcome)) %>% mutate(start=(Outcome != lagged)) -> wc

wc %>% mutate(start=replace_na(start,TRUE)) -> wc

wc %>% mutate(streak_id = cumsum(start)) ->wc

```
Calculate Streak Length and Arrange

```{r}
wc %>%  group_by(rowid,streak_id) %>% mutate(streak=row_number()) %>% ungroup() %>% 
  arrange(.,rowid,DateEvent) %>% rename(PreviousOutcome=lagged) -> wc
```

Previous Result

```{r}
wc %>% group_by(rowid) %>% mutate(StreakLength = lag(streak)) %>% 
  mutate(StreakLength = case_when(PreviousOutcome == 0 ~ -StreakLength, TRUE ~ StreakLength)) -> wc
```





